---
- name: "apt update"
  hosts: all
  become: yes
  become_method: sudo
  tasks:
#  - name: "Update Repository cache"
#    apt:
#      update_cache: true
#      cache_valid_time: 3600
#      force_apt_get: true
  - name: "Update cache & Full system update"
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true
